WiP

diff --git a/common/bin/natfree-update-client-arithmetic b/common/bin/natfree-update-client-arithmetic
--- a/common/bin/natfree-update-client-arithmetic
+++ b/common/bin/natfree-update-client-arithmetic
@@ -1,59 +1,140 @@
 #!/bin/sh
 
+#  Description:
+#
+# natfree client tool to configure /etc/hosts with server configuration
+# The default values of the parameters are obtained sourcing the files
+# (with extension .cfg) from the /etc/natfree-d directory
+#
+
+
 ###############
 # global vars #
 ###############
+# hosts file to write 
+HOSTS_FILE="/etc/hosts.d/arithmetic-server.hosts"
+DEBUG=""
+ACTION=""
+
+# Testing .... HOSTS_FILE="/tmp/arithmetic-server.hosts"
+
 # load common functions
 . /usr/share/natfree-common/natfree-common
 
-# hosts file to write 
-HOSTS_FILE="/etc/hosts.d/arithmetic-server.hosts"
-# Testing .... HOSTS_FILE="/tmp/arithmetic-server.hosts"
-
+CLIENT_IFACE="$(get_client_iface)"
+IP_NUMBER="$(get_ip_number)"
 # List of servers aliases to write (comma separated)
 # TODO: revise list ...
-SRV_ALIASES="server,srv,servidor,fs,mirror,lliurex-mirror,cups,www,ntp,share,jclic-aula,lliurexlab,error,ipxboot,admin-center"
-
-# get default route iface
-GW_IFACE="$(get_gw_iface)"
+SRV_ALIASES="$(get_srv_aliases)"
 
 usage(){
-        die "Usage" "$(basename "$0") [options]" \
-            "       options:" \
-            "           -a            : automagic detection/default parameters" \
-            "           -n NUMBER     : IP number/position in subnet" \
-            "           -i PHYS_IFACE : physical interface name (defaults to $GW_IFACE)"
+        die "Usage" "$(basename "$0") [ OPTIONS ] COMMAND"  \
+            "       OPTIONS:" \
+            "           -i PHYS_IFACE : physical interface name (defaults to $CLIENT_IFACE)" \
+	    "           -n NUMBER     : IP number/position in subnet (defults to $IP_NUMBER)" \
+	    "           -a ALIASES_LIST: comma separated list of names (defaults to $SRV_ALIASES)" \
+            "           -d            : debug mode (verbose)" \
+            "       COMMAND:" \
+            "           UPDATE        : update /etc/hosts file" \
+            "           DESTROY|DELETE: remove data from /etc/hosts file" \
+            "Command names can be used in lower or upper case and abbreviated down to a single letter." \
+            "Where there is ambiguity, dictionary order is used to select a command."
 }
 
 #############
 # functions #
 #############
 main(){
-	# check parameters
-        [ "$1" ] || usage
+        # check parameters
 
-        while [ "$1" ] ; do
+        [ "$1" ] || usage
+        OPTIONS=""
+        while echo "$1" | grep -q "^-" ; do
                 case "$1" in
-                        -n)
-                                shift
-                                SRV_IP_NUMBER="$1"
-                                ;;
                         -i)
+                                [ "$#" -ge 3 ] || usage
                                 shift
-                                GW_IFACE="$1"
+                                CLIENT_IFACE="$(get_client_iface "$1")"
                                 ;;
-                        -a)
-                                # use default
+			-a)
+                                [ "$#" -ge 3 ] || usage
+                                shift
+				SRV_ALIASES="$(get_srv_aliases "$1")"
+				;;
+			-n)
+                                [ "$#" -ge 3 ] || usage
+                                shift
+				IP_NUMBER="$(get_ip_number "$1")"
+				;;
+
+                        -d)
+                                DEBUG="Y"
                                 ;;
                         *)
                                 usage
                                 ;;
                 esac
-		# validate
-                echo "$SRV_IP_NUMBER" |grep -q "^[[:digit:]]\+$" || die "Invalid IP number/position $SRV_IP_NUMBER"
-                [ "$GW_IFACE" ] || die "Undefined physical interface"
-                get_interface_list | grep -qFx "$GW_IFACE" || die "Invalid physical interface $GW_IFACE"
+                OPTIONS="$OPTIONS $1"
+                shift
+        done
 
+        [ "$1" ] || usage
+
+        if [ "$DEBUG" ] ; then
+                cat << EOF
+- Options selected  : [$OPTIONS ]
+- Physical interface: [ $CLIENT_IFACE ]
+- IP number         : [ $IP_NUMBER ]
+- Server aliases    : [ $SRV_ALIASES ]
+EOF
+        fi
+
+        A="$(echo "$1" |tr "[:lower:]" "[:upper:]")"
+
+        case "$A" in
+                D*)
+			ACTION="DESTROY DELETE"
+			OK=""
+			for a in $ACTION ; do
+				if echo "$a" |grep -q "^$A" ; then
+				       OK="Y"
+				fi
+			done
+			[ "$OK" ] || usage
+                        [ -z "$DEBUG" ] || echo "- Action: [ $ACTION ]"
+			;;
+i# recopile necessary data
+
+        # get DNS search domain from resolv.conf (if any)
+        SEARCH_DOMAIN="$(get_domain)"
+        [ -z "$SEARCH_DOMAIN" ] || SEARCH_DOMAIN=":${SEARCH_DOMAIN}"
+
+        # get ip/mask in CIDR notation
+        CIDR="$(get_iface_cidr "$GW_IFACE")"
+        [ "$CIDR" ] || die "Unable to retrieve IP address from $GW_IFACE"
+
+        # get SRV_IP_NUMBER available ip in subnet
+        SRV_IP="$(get_srv_ip "$CIDR" "$SRV_IP_NUMBER")"
+
+        # generate .hosts file
+        echo "# BEGIN arithmetic-server IPs" > "$HOSTS_FILE"
+        generate_hosts "${SRV_IP}:${SRV_ALIASES}${SEARCH_DOMAIN}" >> "$HOSTS_FILE"
+        echo "# END arithmetic-server IPs" >> "$HOSTS_FILE"
+
+        # update /etc/hosts
+        update-hosts
+
+                U*)
+			ACTION="UPDATE"
+                        echo "$ACTION" |grep -q "^$A" || usage
+                        [ -z "$DEBUG" ] || echo "- Action: [ $ACTION ]"
+			;;
+		*)
+			usage
+			;;
+                esac
+
+		# validate
                 shift
         done
 
@@ -78,6 +159,8 @@ main(){
 
 	# update /etc/hosts
 	update-hosts
+
+
 }
 
 ################
diff --git a/common/usr/share/natfree-common/natfree-common b/common/usr/share/natfree-common/natfree-common
--- a/common/usr/share/natfree-common/natfree-common
+++ b/common/usr/share/natfree-common/natfree-common
@@ -4,10 +4,8 @@
 
 # Asume server uses 4th available IP in subnet
 # # and default interface name
-SRV_IP_NUMBER=4
-SRV_VIRTUAL_IFACE="natfree00"
 
-
+CFG_DIR="/etc/natfree.d"
 
 #############
 # functions #
@@ -29,6 +27,14 @@ die(){
         exit 1
 }
 
+get_gw_iface(){
+	# prints first default route iface name
+	LANG=C ip -4 route list 0/0 |head -1 |cut -d ' ' -f 5
+}
+
+
+# load config
+for f in $(ls -1 "$CFG_DIR" |grep "\.cfg$" |sort) ; do . $CFG_DIR/$f ; done
 
 get_interface_list(){
 	LANG=C ip a |sed -ne "/^[[:digit:]]\+:/{s%^[[:digit:]]\+:[[:blank:]]\+%%;s%:.*$%%;s%@.*$%%;p}"
@@ -39,30 +45,94 @@ test_iface(){
 	return 0
 }
 
-get_gw_iface(){
-	# prints first default route iface name
-	LANG=C ip -4 route list 0/0 |head -1 |cut -d ' ' -f 5
+get_var_value(){
+	NEW_VAL="$1"
+	DEF_VAL="$2"
+	[ "$1" ] || NEW_VAL="$DEF_VAL"
+	[ "$2" ] || die "Invalid default value"
+	echo "$NEW_VAL"
+}
+
+get_client_iface(){
+	get_var_value "$1" "$NF_DEF_CLIENT_IFACE"
+}
+
+get_srv_aliases(){
+	get_var_value "$1" "$NF_DEF_SRV_ALIASES"
 }
 
 get_virt_iface(){
-	VIFACE="$SRV_VIRTUAL_IFACE"
-	[ -n "$1" ] || VIFACE="$1"
-	echo "$VIFACE"
+	get_var_value "$1" "$NF_DEF_VIRT_IFACE"
 }
 	
+get_phys_iface(){
+	get_var_value "$1" "$NF_DEF_PHYS_IFACE"
+}
+
+get_ip_number(){
+	IP0="$(echo "$1" |sed -e "s%^+%%")"
+	get_var_value "$IP0" "$NF_DEF_IP_NUMBER"
+}
+
 test_virt_iface(){
 	test_iface "$(get_virt_iface "$1")" || return 1
 	return 0
+}
+
+down_virt_iface(){
+	VIRTUAL_IFACE="$(get_virt_iface "$1")"	# -> VIRT_IFACE_NAME
+        test_iface "$VIRTUAL_IFACE" || die "Virtual interface not created"
+	ip link set "$VIRTUAL_IFACE" down
+}
+
+up_virt_iface(){
+	VIRTUAL_IFACE="$(get_virt_iface "$1")"	# -> VIRT_IFACE_NAME
+        test_iface "$VIRTUAL_IFACE" || die "Virtual interface not created"
+	ip link set "$VIRTUAL_IFACE" up
+}
+
+addr_virt_iface(){
+	SRV_VIRT_IFACE="$(get_virt_iface "$1")"
+	SRV_CIDR="$2"
+	down_virt_iface "$SRV_VIRT_IFACE"
+	# remove all addresses
+	OLD_CIDR_LIST="$(show_addr_virt_iface "$SRV_VIRT_IFACE")"
+	for OLD_CIDR in $OLD_CIDR_LIST; do
+		ip addr del "$OLD_CIDR" dev "$SRV_VIRT_IFACE"
+		OLD_CIDR="$(show_addr_virt_iface "$SRV_VIRT_IFACE")"
+	done
+	
+	ip addr add "$SRV_CIDR" dev "$SRV_VIRT_IFACE"
+	up_virt_iface "$SRV_VIRT_IFACE"
+}
+
+show_virt_iface(){
+	VIRTUAL_IFACE="$(get_virt_iface "$1")"	# -> VIRT_IFACE_NAME
+        test_iface "$VIRTUAL_IFACE" || die "Virtual interface not created"
+	LANG=C ip a show dev "$VIRTUAL_IFACE" |sed -ne  "/^[[:blank:]]*inet[[:blank:]]/{s%^[[:blank:]]*%%;p}"
+}
+
+show_addr_virt_iface(){
+	show_virt_iface "$(get_virt_iface "$1")" |cut -d " " -f2
 }
 
 create_virt_iface(){
 	# create virtual interface over physical interface
 	# currently supports only macvtap mode bridge
 	# parameters:
-	VIRTUAL_IFACE="$1"	# -> VIRT_IFACE_NAME
-	PHYSICAL_IFACE="$2"	# -> PHYS_IFACE
+	VIRTUAL_IFACE="$(get_virt_iface "$1")"	# -> VIRT_IFACE_NAME
+	PHYSICAL_IFACE="$(get_phys_iface "$2")"	# -> PHYS_IFACE
 
 	ip link add "$VIRTUAL_IFACE" link "$PHYSICAL_IFACE" type macvlan mode bridge
+}
+
+delete_virt_iface(){
+	# delete virtual interface over physical interface
+	# parameters:
+	VIRTUAL_IFACE="$(get_virt_iface "$1")"	# -> VIRT_IFACE_NAME
+	PHYSICAL_IFACE="$(get_phys_iface "$2")"	# -> PHYS_IFACE
+	down_virt_iface "$VIRTUAL_IFACE"
+	ip link del "$VIRTUAL_IFACE"
 }
 
 get_domain(){
@@ -76,7 +146,6 @@ get_iface_cidr(){
 	# prints IP/NETMASK from specified interface
 	# parameters:
 	IFACE_NAME="$1"
-
 	LANG=C ip addr show "$IFACE_NAME" |sed -ne "/[[:blank:]]*inet[[:blank:]]/{s%^.*inet[[:blank:]]%%;s%[[:blank:]].*$%%;p}"
 }
 
@@ -161,8 +230,7 @@ get_srv_cidr(){
 	# and returns the nth ip in the related subnet
 	# parameters:
 	CIDR="$1" 	# IP/MASK
-	IP_NUMBER="$2"  # -> subnet IP position
-	
+	IP_NUMBER="$(get_ip_number "$2")"  # -> subnet IP position
 	# separate IP / MASK & calculate HOST_NUMBITS
 	IP="${CIDR%/*}"
 	MASK="${CIDR#*/}"
@@ -171,7 +239,6 @@ get_srv_cidr(){
 	# verify subnet max number of hosts
 	MAX_HOST="$(echo "2^${HOST_NUMBITS} - 1" |bc)"
 	[ $IP_NUMBER -le $MAX_HOST ] || die "Insufficient number of hosts in subnet"
-
 	# convert IP to binary
 	BIN_IP="$(ip2bin "$IP")"
 
@@ -184,7 +251,7 @@ get_srv_cidr(){
 
 	# concatenate to get binary server IP and convert to dot separated format
 	BIN_SRV_IP="${BIN_NET}${BIN_HOST}"
-	printf "$(bin2ip "$BIN_SRV_IP")/$MASK"
+	printf "$(bin2ip "$BIN_SRV_IP")/$MASK\n"
 }
 
 get_srv_ip(){
diff --git a/iface/bin/nafree-iface b/iface/bin/nafree-iface
--- a/iface/bin/nafree-iface
+++ b/iface/bin/nafree-iface
@@ -2,24 +2,26 @@
 
 #  Description:
 #
-# swiss army tool to configure natfree virtual interface
-# natfree interface is This is an if-up.d script to create natfree nework interface when bringing up network
-# The script by itself, creates interface (if needed) without configuration.
-# This script also checks for the availability of "natfree-update-server" configuration tool.
-# If this configuration tool is available (like in a wired natfree lliurex server)
-# natfree-update-server is invoked to configure the interface.
+# Swiss army tool to manage natfree virtual interface.
+# The script mimics in a simplified way the syntax of the ip command,
+# and provides default values for most parameters sourcing files with .cfg extension
+# Run the script with option -h or no parameters to get help.
 #
 
 ###############
 # global vars #
 ###############
-SRV_VIRTUAL_IFACE=""
+SRV_VIRT_IFACE=""
+SRV_PHYS_IFACE=""
 CIDR=""
-METRIC=""
 ACTION=""
+DEBUG=""
 
 # load common functions
 . /usr/share/natfree-common/natfree-common
+SRV_PHYS_IFACE="$(get_phys_iface)"
+SRV_VIRT_IFACE="$(get_virt_iface)"
+
 
 #############
 # functions #
@@ -28,168 +30,128 @@ ACTION=""
 usage(){
         die "Usage" "$(basename "$0") [ OPTIONS ] COMMAND"  \
             "       OPTIONS:" \
-            "           -v VIRT_IFACE : virtual interface name (defaults to $SRV_VIRTUAL_IFACE)" \
+            "           -i PHYS_IFACE : physical interface name (defaults to $SRV_PHYS_IFACE)" \
+            "           -v VIRT_IFACE : virtual interface name (defaults to $SRV_VIRT_IFACE)" \
+	    "           -d            : debug mode (verbose)" \
 	    "       COMMAND:" \
-	    "           CREATE           : create interface" \
-	    "           DELETE           : delete interface" \
-	    "           SHOW             : show interface configuration" \
-	    "           ADDRESS [IP/MASK]: show/set interface network address" \
-	    "           UP               : bring interface up" \
-	    "           DOWN             : bring interface down" \
-	    "           METRIC [NUMBER]  : show/set interface metric value" \
+	    "           CREATE              : create interface" \
+	    "           DELETE              : delete interface" \
+	    "           SHOW                : show interface configuration" \
+	    "           ADDRESS [CIDR|+NUM] : show/set interface network address" \
+	    "           UP                  : bring interface up" \
+	    "           DOWN                : bring interface down" \
             "Command names can be used in lower or upper case and abbreviated down to a single letter." \
-	    " Where there is ambiguity, dictionary order is used to select a command."
+	    "Where there is ambiguity, dictionary order is used to select a command."
 }
 
 main(){
 
-	# check parameters/commands
-	# TODO: get an ordered way to get this ...
+	# check parameters
 
 	[ "$1" ] || usage
-	if [ "$1" = "-v" ] ; then
-		[ "$#" -ge 3 ] || usage
+	OPTIONS=""
+	while echo "$1" | grep -q "^-" ; do
+		case "$1" in
+			-v)
+				[ "$#" -ge 3 ] || usage
+				shift
+				SRV_VIRT_IFACE="$(get_virt_iface "$1")"
+				;;
+			-i)
+				[ "$#" -ge 3 ] || usage
+				shift
+				SRV_PHYS_IFACE="$(get_phys_iface "$1")"
+				;;
+			-d)
+				DEBUG="Y"
+				;;
+			*)
+				usage
+				;;
+		esac
+		OPTIONS="$OPTIONS $1"
 		shift
-		SRV_VIRTUAL_IFACE="$1"
-		shift
+	done
+
+	# check commands
+	[ "$1" ] || usage
+	if [ "$DEBUG" ] ; then
+		cat << EOF
+- Options selected  : [$OPTIONS ]
+- Virtual interface : [ $SRV_VIRT_IFACE ]
+- Physical interface: [ $SRV_PHYS_IFACE ]
+EOF
 	fi
-	SRV_VIRTUAL_IFACE="$(get_virt_iface "$SRV_VIRTUAL_IFACE")"
+
 	A="$(echo "$1" |tr "[:lower:]" "[:upper:]")"
 
 	case "$A" in
 		A*)
 			ACTION="ADDRESS"
+			echo "$ACTION" |grep -q "^$A" || usage
+			[ -z "$DEBUG" ] || echo "- Action: [ $ACTION ]"
+
 			if [ "$#" -ge 2 ] ; then
 				shift
 				CIDR="$1"
-			fi
-			test_iface "$SRV_VIRTUAL_IFACE" || die "Virtual interface not created"
-			if [ "$CIDR" ] ; then
-				addr_virt_iface "$SRV_VIRTUAL_IFACE" "$CIDR"
+				if echo "$1" |grep -q "^[[:digit:]]\+$" ; then
+					IP_NUM="$1"
+					PCIDR="$(get_iface_cidr "$SRV_PHYS_IFACE")"
+					CIDR="$(get_srv_cidr "$PCIDR" "$IP_NUM")"
+					[ -z "$DEBUG" ] || echo "  -- IP number: [ $IP_NUM of $PCIDR ]"
+				fi
+
+				if echo "$CIDR" |grep -q "^\([[:digit:]]\+\.\)\{3\}[[:digit:]]\+/[[:digit:]]\+$" ; then
+					[ -z "$DEBUG" ] || echo "  --  cidr: [ $CIDR ]"
+					addr_virt_iface "$SRV_VIRT_IFACE" "$CIDR"
+				else
+					die "Invalid parameter: $CIDR"
+				fi
 			else
-				show_addr_virt_iface "$SRV_VIRTUAL_IFACE"
+				show_addr_virt_iface "$SRV_VIRT_IFACE"
 			fi
 			;;
 		C*)
 			ACTION="CREATE"
-			if test_iface "$SRV_VIRTUAL_IFACE" ; then
-				die "Virtual interface already created"
-			else
-				create_virt_iface "$SRV_VIRTUAL_IFACE"
-			fi
+			echo "$ACTION" |grep -q "^$A" || usage
+			[ -z "$DEBUG" ] || echo "- Action: [ $ACTION ]"
+			create_virt_iface "$SRV_VIRT_IFACE" "$SRV_PHYS_IFACE"
 			;;
 		D|DE*)
 			ACTION="DELETE"
-			if test_iface "$SRV_VIRTUAL_IFACE" ; then
-				die "Virtual interface already created"
+			echo "$ACTION" |grep -q "^$A" || usage
+			[ -z "$DEBUG" ] || echo "- Action: [ $ACTION ]"
+			if test_iface "$SRV_VIRT_IFACE" ; then
+				delete_virt_iface "$SRV_VIRT_IFACE"
 			else
-				create_virt_iface "$SRV_VIRTUAL_IFACE"
+				die "Virtual interface not created"
 			fi
 			;;
 		DO*)
 			ACTION="DOWN"
-			;;
-		M*)
-			ACTION="METRIC"
-			if [ "$#" -ge 2 ] ; then
-				shift
-				METRIC="$1"
-			fi
+			echo "$ACTION" |grep -q "^$A" || usage
+			[ -z "$DEBUG" ] || echo "- Action: [ $ACTION ]"
+			test_iface "$SRV_VIRT_IFACE" || die "Virtual interface not created"
+			down_virt_iface "$SRV_VIRT_IFACE"
 			;;
 		S*)
 			ACTION="SHOW"
+			echo "$ACTION" |grep -q "^$A" || usage
+			[ -z "$DEBUG" ] || echo "- Action: [ $ACTION ]"
+			show_virt_iface "$SRV_VIRT_IFACE"
 			;;
 		U*)
-			ACTION="UPPER"
+			ACTION="UP"
+			echo "$ACTION" |grep -q "^$A" || usage
+			[ -z "$DEBUG" ] || echo "- Action: [ $ACTION ]"
+			test_iface "$SRV_VIRT_IFACE" || die "Virtual interface not created"
+			up_virt_iface "$SRV_VIRT_IFACE"
 			;;
 		*)
 			usage
 			;;
 	esac
 
-	# do the real job ...
-	case "$ACTION" in
-		ADDRESS)
-			test_iface "$SRV_VIRTUAL_IFACE" || die "Virtual interface not created"
-			if [ "$CIDR" ] ; then
-				addr_virt_iface "$SRV_VIRTUAL_IFACE" "$CIDR"
-			else
-				show_addr_virt_iface "$SRV_VIRTUAL_IFACE"
-			fi
-			;;
-		C*)
-			ACTION="CREATE"
-			;;
-		D|DE*)
-			ACTION="DELETE"
-			;;
-		DO*)
-			ACTION="DOWN"
-			;;
-		M*)
-			ACTION="METRIC"
-			if [ "$#" -ge 2 ] ; then
-				shift
-				METRIC="$1"
-			fi
-			;;
-		S*)
-			ACTION="SHOW"
-			;;
-		U*)
-			ACTION="UPPER"
-			;;
-		*)
-			usage
-			;;
-	esac
-
-
-
-	# recopile necessary data
-
-	# get ip/mask in CIDR notation
-	CIDR="$(get_iface_cidr "$GW_IFACE")"
-	[ "$CIDR" ] || die "Unable to retrieve IP address from $GW_IFACE"
-
-	# get SRV_IP_NUMBER available ip in subnet
-	SRV_CIDR="$(get_srv_cidr "$CIDR" "$SRV_IP_NUMBER")"
-
-	# check existence of SRV_VIRTUAL_IFACE and create if needed
-	if ! get_interface_list | grep -qFx "$SRV_VIRTUAL_IFACE" ; then
-		create_virt_iface "$SRV_VIRTUAL_IFACE" "$GW_IFACE"
-		# test creation
-		get_interface_list | grep -qFx "$SRV_VIRTUAL_IFACE" || die "Unable to create virtual interface $SRV_VIRTUAL_IFACE"
-	fi
-
-	# assign SRV_IP to virtual interface
-	# TODO: test this code !!!!!!!
-	ip link set dev "$SRV_VIRTUAL_IFACE" down
-	ip addr add "$SRV_CIDR" dev "$SRV_VIRTUAL_IFACE"
-	ip link set dev "$SRV_VIRTUAL_IFACE" up
-
-	# extract SRV_IP
-	SRV_IP="${SRV_CIDR%/*}"
-
-	# update server n4d variables
-	# TODO: please avoid this dirty trick ...
-	# BEGIN 
-	N4DVARS_DIR="/var/lib/n4d/variables"
-	N4DVARS_FILES="SRV_IP,$SRV_IP CLIENT_LDAP_URI,ldaps://$SRV_IP CLIENT_LDAP_URI_NOSSL,ldap://$SRV_IP"
-	N4DVARS_BACKUP_DIR="/tmp/n4dvars-backup/$(date "+%s")"
-	mkdir -p "$N4DVARS_BACKUP_DIR"
-	for f in $N4DVARS_FILES ; do
-		VAR_FILE="${N4DVARS_DIR}/${f%,*}"
-		VAR_VALUE="${f#*,}"
-		if [ -e "$VAR_FILE" ] ; then
-			# make a copy
-			BASENAME_FILE="$(basename "$VAR_FILE")"
-			cp "$VAR_FILE" "$N4DVARS_BACKUP_DIR/${BASENAME_FILE}"
-			sed -i -e "/\"value\":/s%:.*$%: \"$VAR_VALUE\",%" "$VAR_FILE"
-		fi
-	done
-	service n4d restart
-	# END
 
 }
 
